# Task to configure repos, update, upgrade, and autoremove software with APT 

- name: "Download Microsoft signing key + repository"
  become: false
  get_url:
    dest: "/home/{{ currentUser.stdout }}/.temp/packages-microsoft-prod.deb"
    url: "https://packages.microsoft.com/config/ubuntu/{{ osVersion.stdout }}/packages-microsoft-prod.deb"

- name: "Download and install Intel keyring"
  become: true
  shell:
    cmd: "wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null"

- name: "Download and install Wine keyring"
  become: true
  shell:
    cmd: "wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key"

- name: "Add Intel APT repository"
  become: true
  shell:
    cmd: "echo 'deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main' | sudo tee /etc/apt/sources.list.d/oneAPI.list"

- name: "Add Wine APT repository"
  become: true
  shell:
    # ONLY FOR Ubuntu 22.04
    cmd: "wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources"

- name: "Install Microsoft signing key + repository"
  become: true
  apt:
    deb: "/home/{{ currentUser.stdout }}/.temp/packages-microsoft-prod.deb"

- name: "Add SWI-Prolog PPA"
  become: true
  apt_repository:
    repo: "ppa:swi-prolog/stable"

- name: "Add Racket PPA"
  become: true
  apt_repository:
    repo: "ppa:plt/racket"

- name: "Upgrade Packages"
  become: true
  apt:
    upgrade: safe
    autoremove: true
    purge: true

- name: "Upgrade System Packages"
  become: true
  apt:
    upgrade: full
    autoremove: true
    purge: true

- name: "Upgrade Distribution"
  become: true
  apt:
    upgrade: dist
    autoremove: true
    purge: true

- name: "Update APT Cache"
  become: true
  apt:
    update_cache: true
    autoclean: true
