- name: "Upgrade Packages"
  become: true
  apt:
    upgrade: safe
    autoremove: true
    purge: true

- name: "Upgrade System Packages"
  become: true
  apt:
    upgrade: full
    autoremove: true
    purge: true

- name: "Upgrade Distribution"
  become: true
  apt:
    upgrade: dist
    autoremove: true
    purge: true
