---
  - name: "Setup Linux"
    hosts: [localhost]
    connection: local

    tasks:
      - import_tasks: tasks/ansible/variables.yml
      - import_tasks: tasks/configure/home.yml

        # APT related tasks
      - import_tasks: tasks/configure/apt.yml
      - import_tasks: tasks/install/managers/apt.yml

      # Linuxbrew related tasks
      - import_tasks: tasks/install/linuxbrew.yml
        when:
          "not linuxbrewDir.stat.exists"
      - import_tasks: tasks/install/managers/linuxbrew.yml

      # Ada Alire related tasks
      - import_tasks: tasks/install/alire.yml
        when:
          "not alireExecutable.stat.exists"
      - import_tasks: tasks/install/managers/alire.yml
        when:
          "alireExecutable.stat.exists"

      # Nim choosenim related tasks
      - import_tasks: tasks/install/choosenim.yml
        when:
          "not choosenimDir.stat.exists"

      # Elm related tasks
      - import_tasks: tasks/install/elm.yml
        when:
          "not elmExecutable.stat.exists"

      # Basic FBC related tasks
      - import_tasks: tasks/install/fbc.yml
        when:
          "not fbcExecutable.stat.exists"

      # ZSH oh-my-zsh related tasks
      - import_tasks: tasks/install/omz.yml
        when:
          "not omzDir.stat.exists"

      # R r-rig related tasks
      - import_tasks: tasks/install/rig.yml
        when:
          "not rigExecutable.stat.exists"
      - import_tasks: tasks/install/managers/rig.yml
        when:
          "rigExecutable.stat.exists"

      # Rust rustup related tasks
      - import_tasks: tasks/install/rustup.yml
        when:
          "not rustupDir.stat.exists"

      # JVM SDKMan related tasks
      - import_tasks: tasks/install/sdkman.yml
        when:
          "not sdkmanDir.stat.exists"

      # Tiny C Compiler (TCC) related tasks
      - import_tasks: tasks/install/tcc.yml
        when:
          "not tccExecutable.stat.exists"

      # V related tasks
      - import_tasks: tasks/install/v.yml
        when:
          "not vDir.stat.exists"

      # Vim vim-plug related tasks
      - import_tasks: tasks/install/vimplug.yml
        when:
          "not vimplugExecutable.stat.exists"
      
      # Copy dotfiles to the $HOME directory
      - import_tasks: tasks/system/dotfiles.yml

    

    # Configuring the user related tasks
      # - name: "Create SSH key"
      #   become: false
      #   shell:
      #     cmd: "ssh-keygen -b 3072 -t rsa -f ~/.ssh/id_rsa -q -N ''"
