---
  - name: "Setup Linux"
    hosts: [localhost]
    connection: local

    tasks:
      - import_tasks: tasks/setAnsibleVariables.yml
      - import_tasks: tasks/configureHomeDirectory.yml
      - import_tasks: tasks/installElm.yml
        # - import_tasks: tasks/installSDKMan.yml
        # - import_tasks: tasks/installRig.yml
        # - import_tasks: tasks/installLinuxbrew.yml
        # - import_tasks: tasks/configureAPT.yml
        # - import_tasks: tasks/installFreeBasicCompiler.yml
