---
  - name: "Setup Linux"
    hosts: [localhost]
    connection: local

    tasks:
      - import_tasks: tasks/setAnsibleVariables.yml
      - import_tasks: tasks/configureHomeDirectory.yml
      - import_tasks: tasks/configureAPT.yml
