---
  - name: "Post-installation Linux Configuration"
    hosts: [localhost]
    connection: local

    tasks:
      - import_tasks: tasks/ansible/variables.yml
      - import_tasks: tasks/configure/shells.yml
      - import_tasks: tasks/configure/ssh.yml
      - import_tasks: tasks/install/managers/asdf.yml
      - import_tasks: tasks/install/managers/juliaup.yml
      - import_tasks: tasks/install/managers/luaver.yml
      - import_tasks: tasks/install/managers/nvm.yml
      - import_tasks: tasks/install/managers/rbenv.yml
      # lynis
      # pyenv
      # bun
