# Task to configure repos, update, upgrade, and autoremove software with APT 

- name: "Download Microsoft signing key + repository"
  become: false
  get_url:
    dest: "/home/{{ currentUser.stdout }}/.temp/packages-microsoft-prod.deb"
    url: "https://packages.microsoft.com/config/ubuntu/{{ osVersion.stdout }}/packages-microsoft-prod.deb"
  
- name: "Install Microsoft signing key + repository"
  become: true
  apt:
    deb: "/home/{{ currentUser.stdout }}/.temp/packages-microsoft-prod.deb"

- name: "Add SWI-Prolog PPA"
  apt_repository:
    repo: "ppa:swi-prolog/stable"

- name: "Upgrade Packages"
  become: true
  apt:
    upgrade: safe
    autoremove: true
    purge: true

- name: "Upgrade System Packages"
  become: true
  apt:
    upgrade: full
    autoremove: true
    purge: true

- name: "Upgrade Distribution"
  become: true
  apt:
    upgrade: dist
    autoremove: true
    purge: true

- name: "Update APT Cache"
  become: true
  apt:
    update_cache: true
    autoclean: true
