# Playbook to install rustup

- name: "Download rustup installer"
  become: false
  get_url:
    dest: "/home/{{ currentUser.stdout }}/.temp/rustupInstaller.sh"
    mode: "+x"
    url: "https://sh.rustup.rs"

- name: "Install rustup"
  become: false
  shell:
    chdir: "/home/{{ currentUser.stdout }}/.temp"
    cmd: "./rustupInstaller.sh -y --no-modify-path"

- name: "Move rustup"
  become: false
  shell:
    chdir: "/home/{{ currentUser.stdout }}"
    cmd: "mv .rustup /home/{{ currentUser.stdout }}/.local/bin/rustup"

- name: "Move cargo"
  become: false
  shell:
    chdir: "/home/{{ currentUser.stdout }}"
    cmd: "mv .cargo /home/{{ currentUser.stdout }}/.local/bin/cargo"
