# Install Fossil scm 

- name: "Download Fossil scm source code"
  become: false
  get_url:
    dest: "/home/{{ currentUser.stdout }}/.temp/fossil.tar.gz"
    url: "https://fossil-scm.org/home/tarball/47362306a7dd7c6fc3cab77cebe5d25469b0a9448479d9718eb5c49c8337b29/fossil-src-2.23.tar.gz"

- name: "Decompress Fossil scm"
  become: false
  unarchive:
    copy: false
    dest: "/home/{{ currentUser.stdout }}/.temp"
    src: "/home/{{ currentUser.stdout }}/.temp/fossil.tar.gz"

- name: "Compile Fossil scm"
  become: false
  shell:
    chdir: "/home/{{ currentUser.stdout }}/.temp/fossil-src-2.23"
    cmd: "./configure; make"

- name: "Install Fossil scm"
  become: false
  copy:
    dest: "/home/{{ currentUser.stdout }}/.local/bin/fossil"
    mode: "+x"
    src: "/home/{{ currentUser.stdout }}/.temp/fossil-src-2.23/fossil"

