# Playbook to install the FreeBasic Compiler to the ~/.local/bin directory

- name: "Download FreeBasic Compiler"
  become: false
  get_url:
    dest: "/home/{{ currentUser.stdout }}/.temp/fbc.tar.gz"
    url: "https://newcontinuum.dl.sourceforge.net/project/fbc/FreeBASIC-1.10.0/Binaries-Linux/FreeBASIC-1.10.0-linux-x86_64.tar.gz"

- name: "Decompress FreeBasic Compiler"
  become: false
  unarchive:
    copy: false
    dest: "/home/{{ currentUser.stdout }}/.temp"
    src: "/home/{{ currentUser.stdout }}/.temp/fbc.tar.gz"

- name: "Install FreeBasic Compiler"
  become: false
  shell:
    chdir: "/home/{{ currentUser.stdout }}/.temp/FreeBASIC-1.10.0-linux-x86_64"
    cmd: "./install.sh -i /home/{{ currentUser.stdout }}/.local"
