# Set variables to be referenced within Ansible tasks

- name: "Get current username"
  command: whoami
  register: currentUser

- name: "Get Ubuntu version"
  command: if command -v lsb_release &> /dev/null; then lsb_release -r -s; else grep -oP '(?<=^VERSION_ID=).+' /etc/os-release | tr -d '"'; fi
  register: osVersion
