# Set variables to be referenced within Ansible tasks

- name: "Get current username"
  command: whoami
  register: currentUser

- name: "Get Raspberry Pi OS version"
  command: 'lsb_release -r -s'
  register: osVersion
