# Set variables to be referenced within Ansible tasks

- name: "Get current username"
  command: whoami
  register: currentUser

- name: "Get Ubuntu version"
  command: 'lsb_release -r -s'
  register: osVersion

# Register executables

- name: "Set Alire executable"
  stat:
    path: "/home/{{ currentUser.stdout }}/.local/bin/alr"
  register: alireExecutable

- name: "Set Elm executable"
  stat:
    path: "/home/{{ currentUser.stdout }}/.local/bin/elm"
  register: elmExecutable

- name: "Set Free Basic Compiler executable"
  stat:
    path: "/home/{{ currentUser.stdout }}/.local/bin/fbc"
  register: fbcExecutable

- name: "Set r-rig executable"
  stat:
    path: "/home/{{ currentUser.stdout }}/.local/bin/rig"
  register: rigExecutable

- name: "Set tcc executable"
  stat:
    path: "/home/{{ currentUser.stdout }}/.local/bin/tcc"
  register: tccExecutable

- name: "Set vim-plug executable"
  stat:
    path: "/home/{{ currentUser.stdout }}/.vim/autoload/plug.vim"
  register: vimplugExecutable

# Register directories

- name: "Set choosenim directory"
  stat:
    path: "/home/{{ currentUser.stdout }}/.choosenim"
  register: choosenimDir

- name: "Set Linuxbrew directory"
  stat:
    path: "/home/linuxbrew/.linuxbrew"
  register: linuxbrewDir

- name: "Set OMZ directory"
  stat:
    path: "/home/{{ currentUser.stdout }}/.oh-my-zsh"
  register: omzDir

- name: "Set rustup directory"
  stat:
    path: "/home/{{ currentUser.stdout }}/.local/bin/cargo"
  register: rustupDir

- name: "Set SDKMan directory"
  stat:
    path: "/home/{{ currentUser.stdout }}/.local/bin/sdkman"
  register: sdkmanDir

- name: "Set V directory"
  stat:
    path: "/home/{{ currentUser.stdout }}/.local/bin/v"
  register: vDir
