# Copy dotfiles to $HOME directory

- name: "Copy dotfiles to $HOME directory"
  become: false
  shell:
    chdir: "dotfiles"
    cmd: "find -maxdepth 1 -type f | xargs -I % cp % /home/{{ currentUser.stdout }}/%"
