- name: "Install node"
  become: false
  shell:
    cmd: "source /home/{{ currentUser.stdout }}/.nvm/nvm.sh && nvm install node"
    executable: "/bin/bash"

- name: "Use node"
  become: false
  shell:
    cmd: "source /home/{{ currentUser.stdout }}/.nvm/nvm.sh && nvm use node"
    executable: "/bin/bash"
