---
  - name: "Setup Raspberry Pi 3 B+ w/ Raspberry Pi OS"
    hosts: all
    connection: ssh

    tasks:
      - import_tasks: tasks/ansible/variables.yml
      - import_tasks: tasks/configure/home.yml

        # APT related tasks
      - import_tasks: tasks/configure/apt.yml
      
        # Docker related tasks
      - import_tasks: tasks/install/docker.yml

      # # Copy dotfiles to the $HOME directory
      # - import_tasks: tasks/system/dotfiles.yml
