- name: "Install APT software"
  become: true
  apt:
    name: "{{ aptSoftware }}"

- name: "Install software from Racket APT repository"
  become: true
  apt:
    name: "{{ racketAPTRepoSoftware }}"

- name: "Install software from SWI-Prolog APT repository"
  become: true
  apt:
    name: "{{ swiAPTRepoSoftware }}"

- name: "Install software from Microsoft APT repository"
  become: true
  apt:
    name: "{{ microsoftAPTRepoSoftware }}"

- name: "Install software from Intel APT repository"
  become: true
  shell:
    cmd: "apt install intel-aikit intel-basekit intel-hpckit -y"

- name: "Install Wine"
  become: true
  apt:
    name: "winehq-stable"
    install_recommends: true
