# Install r-rig

- name: "Download latest r-rig release"
  become: false
  get_url:
    dest: "/home/{{ currentUser.stdout }}/.temp/r-rig.tar.gz"
    url: "https://github.com/r-lib/rig/releases/download/latest/rig-linux-latest.tar.gz"
  when: "not rigExecutable.stat.exists"

- name: "Decompress r-rig"
  become: false
  unarchive:
    copy: false
    dest: "/home/{{ currentUser.stdout }}/.local"
    src: "/home/{{ currentUser.stdout }}/.temp/r-rig.tar.gz"
  when: "not rigExecutable.stat.exists"
