# Install Alire (Ada package manager)

- name: "Install GNAT"
  become: false
  shell:
    cmd: "{{ alireExecutable.stat.path }} toolchain --install gnat"
  when: "alireExecutable.stat.exists"

- name: "Install gprbuild"
  become: false
  shell:
    cmd: "{{ alireExecutable.stat.path }} toolchain --install gprbuild"
  when: "alireExecutable.stat.exists"
