# Task to configure repos, update, upgrade, and autoremove software with APT 
- name: "Download and install Wine keyring"
  become: true
  shell:
    cmd: "wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key"

- name: "Add Wine APT repository"
  become: true
  shell:
    # ONLY FOR Ubuntu 22.04
    cmd: "wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources"

- name: "Add OBS APT repository"
  become: true
  apt_repository:
    repo: "ppa:obsproject/obs-studio"

- name: "Update APT Cache"
  become: true
  apt:
    update_cache: true
    autoclean: true

- name: "Upgrade Packages"
  become: true
  apt:
    upgrade: safe
    autoremove: true
    purge: true

- name: "Upgrade System Packages"
  become: true
  apt:
    upgrade: full
    autoremove: true
    purge: true

- name: "Upgrade Distribution"
  become: true
  apt:
    upgrade: dist
    autoremove: true
    purge: true
