- name: "Install Kotlin"
  become: false
  shell:
    cmd: "source /home/{{ currentUser.stdout }}/.local/bin/sdkman/bin/sdkman-init.sh && sdk install kotlin"
    executable: "/bin/bash"

- name: "Install SBT"
  become: false
  shell:
    cmd: "source /home/{{ currentUser.stdout }}/.local/bin/sdkman/bin/sdkman-init.sh && sdk install sbt"
    executable: "/bin/bash"

- name: "Install Scala"
  become: false
  shell:
    cmd: "source /home/{{ currentUser.stdout }}/.local/bin/sdkman/bin/sdkman-init.sh && sdk install scala"
    executable: "/bin/bash"

- name: "Install Schemacrawler"
  become: false
  shell:
    cmd: "source /home/{{ currentUser.stdout }}/.local/bin/sdkman/bin/sdkman-init.sh && sdk install schemacrawler "
    executable: "/bin/bash"

- name: "Install JDK 8"
  become: false
  shell:
    cmd: "source /home/{{ currentUser.stdout }}/.local/bin/sdkman/bin/sdkman-init.sh && sdk install java 8.0.402-tem"
    executable: "/bin/bash"

- name: "Install JDK 11"
  become: false
  shell:
    cmd: "source /home/{{ currentUser.stdout }}/.local/bin/sdkman/bin/sdkman-init.sh && sdk install java 11.0.22-tem"
    executable: "/bin/bash"

- name: "Install JDK 17"
  become: false
  shell:
    cmd: "source /home/{{ currentUser.stdout }}/.local/bin/sdkman/bin/sdkman-init.sh  && sdk install java 17.0.10-tem"
    executable: "/bin/bash"

- name: "Install JDK 21"
  become: false
  shell:
    cmd: "source /home/{{ currentUser.stdout }}/.local/bin/sdkman/bin/sdkman-init.sh  && sdk install java 21.0.2-tem"
    executable: "/bin/bash"
